### ISSUE TITLE
Error compiling objects for extension?

### ISSUE THREAD

**Issue by rxqy** [aliutkus/torchsearchsorted#19]
Hi, thanks for the beautiful implementation here.
I'm trying to install this module, but I got the following error:
```
  ERROR: Command errored out with exit status 1:                                              
   command: /root/Anacondas/anaconda3/envs/nerf/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/p300/Code/gnerf-pytorch/torchsearchsorted/setup.py'"'"'; __file__='"'"'/p300/Code/gnerf-pytorch/torchsearchsorted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-37xwwr5z       cwd: /p300/Code/gnerf-pytorch/torchsearchsorted/
...

      File "/root/Anacondas/anaconda3/envs/nerf/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
```
I only copy-pasted the start and the end of the whole error cuz they are too long..
The whole error logs are attached below:
[err.log](https://github.com/aliutkus/torchsearchsorted/files/4619639/err.log)

BTW, I'm running with pytorch 1.5, RTX2080tis
tried pytorch 1.3 or 1.4, but no luck
running `nvcc --version` gives me:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019    
Cuda compilation tools, release 10.1, V10.1.243    
```

Any help?

**Comment by aliutkus** [comment]
ok, thanks a lot, the error log is very helpful. 
I'd say It looks like there was some deprecation going on since the module was created.
It should be possible to update the code to meet the newest requirements.

My bet is: the lines that need updating are there: https://github.com/aliutkus/torchsearchsorted/blob/1e0ffc3e0663ffda318b4e28348efd90313d08f3/src/cuda/searchsorted_cuda_kernel.cu#L134
`.data` should be replaced by `.data_ptr` and maybe some other things should be done here according to the definition of the AT_DISPATCH_ALL_TYPE, on which I see many warnings. Its definition is [there](https://github.com/pytorch/pytorch/blob/54c16b44cf433d196e68fad8069274f2b61052d9/aten/src/ATen/Dispatch.h#L83)  

I don't have much time right now to investigate, feel free to PR if you find your way around, sorry for this. I will anyway check this myself as soon as I get a bit of time. This framework is moving fast, internally =)

**Comment by aliutkus** [comment]
ok, I tried to update through commit f6ace753e77a9ac0e091bdedc8287212aff61655

it does work again on my side, with pytorch 1.5 and cuda 10.1

> be careful that nvcc still says that it requires g++ / gcc no greater than v8 on my side ! So I still have to create symbolic links to these versions in the cuda/bin dir

**Comment by rxqy** [comment]
@aliutkus Also work for me. Many thanks!!
